# Generated by Django 3.1.4 on 2020-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='کد ')),
                ('name', models.CharField(max_length=400, verbose_name='نام')),
                ('description', models.TextField(max_length=500, verbose_name='مشخصات')),
                ('box_description', models.TextField(max_length=500, verbose_name='مشخصات بسته بندی')),
                ('foreign_purchase', models.BooleanField(default=False, verbose_name=' خرید خارجی ')),
                ('standard_purchase', models.BooleanField(default=False, verbose_name='  خرید استاندارد ')),
                ('image', models.ImageField(upload_to='image/material', verbose_name='تصویر قطعه')),
                ('schematic_img', models.ImageField(upload_to='image/schematic', verbose_name='تصویر شماتیک')),
                ('box_img', models.ImageField(upload_to='image/box', verbose_name='تصویر بسته بندی')),
                ('tag', models.TextField(max_length=500, verbose_name='برچسب ها ')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
    ]
