# Generated by Django 3.1.4 on 2020-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201215_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='box_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='مشخصات بسته بندی'),
        ),
        migrations.AlterField(
            model_name='material',
            name='box_img',
            field=models.ImageField(blank=True, null=True, upload_to='image/box', verbose_name='تصویر بسته بندی'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='App.Category', verbose_name='دسته بندی '),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد '),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='مشخصات'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/material', verbose_name='تصویر قطعه'),
        ),
        migrations.AlterField(
            model_name='material',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='App.Product', verbose_name='موارد کاربرد '),
        ),
        migrations.AlterField(
            model_name='material',
            name='schematic_img',
            field=models.ImageField(blank=True, null=True, upload_to='image/schematic', verbose_name='تصویر شماتیک'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, to='App.Supplier', verbose_name='تامین کنند '),
        ),
        migrations.AlterField(
            model_name='material',
            name='tag',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='برچسب ها '),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد '),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن'),
        ),
    ]
