# Generated by Django 3.1.4 on 2020-12-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20201229_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='فایل نقشه قطعه'),
        ),
        migrations.AlterField(
            model_name='material',
            name='schematic_img',
            field=models.ImageField(blank=True, null=True, upload_to='image/schematic', verbose_name='تصویر دوم'),
        ),
    ]
