# Generated by Django 3.1.4 on 2020-12-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201230_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='schematic_img',
        ),
    ]
