# Generated by Django 3.1.4 on 2020-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_material_schematic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='box_img',
            field=models.ImageField(blank=True, default='image/Default.png', null=True, upload_to='image/box', verbose_name='تصویر بسته بندی'),
        ),
    ]
