# Generated by Django 3.1.4 on 2020-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201230_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, default='image/Default.png', null=True, upload_to='image/material', verbose_name='تصویر قطعه'),
        ),
    ]
