# Generated by Django 3.1.4 on 2020-12-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20201230_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, max_length=10, null=True, verbose_name=' ضریب مصرف ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product', verbose_name=' موارد کاربرد  ')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='rate',
            field=models.ManyToManyField(blank=True, null=True, to='App.Rate', verbose_name=' ضریب مصرف  '),
        ),
    ]
