# Generated by Django 3.1.4 on 2020-12-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20201230_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': ' ضریب مصرف', 'verbose_name_plural': ' ضرایب مصرف'},
        ),
    ]
