# Generated by Django 3.1.4 on 2020-12-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20201230_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=' ضریب مصرف '),
        ),
    ]
