# Generated by Django 3.1.4 on 2020-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20201230_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ManyToManyField(to='App.Category', verbose_name='دسته بندی '),
        ),
        migrations.AlterField(
            model_name='material',
            name='product',
            field=models.ManyToManyField(to='App.Product', verbose_name='موارد کاربرد '),
        ),
        migrations.AlterField(
            model_name='material',
            name='rate',
            field=models.ManyToManyField(to='App.Rate', verbose_name=' ضریب مصرف  '),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ManyToManyField(to='App.Supplier', verbose_name='تامین کنند '),
        ),
    ]
