# Generated by Django 3.1.4 on 2020-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20201230_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/Default.png', null=True, upload_to='image/product', verbose_name='تصویر'),
        ),
    ]
