# Generated by Django 3.1.4 on 2021-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20201230_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='rate',
            field=models.ManyToManyField(blank=True, null=True, to='App.Rate', verbose_name=' ضریب مصرف  '),
        ),
    ]
